image: node

variables:
 GIT_SUBMODULE_STRATEGY: recursive

build:
  script:
  - ./build.sh
  artifacts:
    paths:
    - eaas-frontend-admin/dist/
    - eaas-frontend-user/dist/
    - citar-headless-client/dist/

build_multi_user_admin_ui:
  script:
  - cd eaas-frontend-admin
  - mv src/public/auth.env.template src/public/auth.env
  - sed 's/myClientId/'"$UI_CLIENT_ID"'/g' src/public/auth.env
  - npm install
  - npm run build
  artifacts:
    paths:
    - eaas-frontend-admin/dist/
