image: node

variables:
 GIT_SUBMODULE_STRATEGY: recursive

build:
  script:
  - ./build.sh
  artifacts:
    paths:
    - eaas-frontend-admin/dist/
    - eaas-frontend-user/dist/
    - citar-headless-client/dist/

build_multi_user_admin_ui:
  script:
  - cd eaas-frontend-admin
  - mv auth.env.template auth.env
  - sed -i 's/myClientId/'"$UI_CLIENT_ID"'/g' auth.env
  - npm install
  - npm run build
  only:
   refs:
     - master
   variables:
     - $CI_PROJECT_NAMESPACE == "openslx"
  artifacts:
    paths:
    - eaas-frontend-admin/dist/
