image: node

variables:
 GIT_SUBMODULE_STRATEGY: recursive

build:
  script:
  - ./build.sh
  artifacts:
    paths:
    - eaas-frontend-admin/dist/
    - landing-page/dist/
    - eaasi-public-portal/dist/

build_multi_user_admin_ui:
  script:
  - mv eaas-frontend-admin/auth.env.template eaas-frontend-admin/auth.env
  - sed -i 's/myClientId/'"$UI_CLIENT_ID"'/g' eaas-frontend-admin/auth.env
  - ./build.sh
  only:
   refs:
     - master
   variables:
     - $CI_PROJECT_NAMESPACE == "openslx"
  artifacts:
    paths:
    - eaas-frontend-admin/dist/
    - landing-page/dist/
    - eaasi-public-portal

build-citar:
 stage: build
 before_script:
  - apt-get update -qq && apt-get install -y rsync sshpass
 script:
  - git submodule init && git submodule update --remote --merge
  - echo $CONFIG > eaas-frontend-admin/src/public/config.json
  - echo $CONFIG > landing-page/src/public/config.json
  - ./build-citar.sh
  - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O /builds/openslx/demo-ui/eaas-frontend-admin/dist/ gitlab@$CITAR_SERVER:/mnt/data/citar-demo/demo-ui/eaas-frontend-admin/dist/
  - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O /builds/openslx/demo-ui/landing-page/dist/ gitlab@$CITAR_SERVER:/mnt/data/citar-demo/demo-ui/landing-page/dist/
 only:
  refs:
   - citar-release
