image: node:8

build:
 stage: build
 script:
 - git submodule init && git submodule update
 - echo $CONFIG > eaas-frontend-admin/src/public/config.json
 - echo $CONFIG > citar-headless-client/src/public/config.json
 - ./build-citar.sh
 
 
 cache:
  paths:
  - eaas-frontend-admin/node_modules
  - citar-headless-client/node_modules
