image: node:8

build:
 stage: build
 script:
 - cd eaas-frontend-admin
 - git submodule init
 - git submodule update
 - npm install
 - npm run build
 
 
 cache:
  paths:
  - demo-ui/eaas-frontend-admin/node_modules
