image: node:8

before_script:
  - apt-get update -qq && apt-get install -y rsync sshpass

build:
 stage: build
 script:
 - git submodule init && git submodule update --remote --merge
 - echo $CONFIG > eaas-frontend-admin/src/public/config.json
 - echo $CONFIG > citar-headless-client/src/public/config.json
 - ./build-citar.sh
 - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O /builds/openslx/demo-ui/eaas-frontend-admin/dist/ gitlab@$CITAR_SERVER:/mnt/data/citar-demo/demo-ui/eaas-frontend-admin/dist/
 - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O /builds/openslx/demo-ui/citar-headless-client/dist/ gitlab@$CITAR_SERVER:/mnt/data/citar-demo/demo-ui/citar-headless-client/dist/

