name: Playwright Tests
on:
  - push
  - workflow_dispatch

env:
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - name: Print branch name
        shell: bash
        run: echo "${GITHUB_HEAD_REF}"
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build Frontend
        run: ./build.sh
        # TODO check if eaas installer can see build dir
      - uses: emulation-as-a-service/eaas-installer@github-actions
        with:
          isBackend: false
          branch: ${GITHUB_HEAD_REF}
          # TODO build UI and server locally and pass the directories to installer
      - name: Install dependencies
        run: npm ci
        working-directory: ./playwright-tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./playwright-tests
      - name: Run Playwright tests
        run: npx playwright test --project=chromium
        working-directory: ./playwright-tests
      - uses: actions/upload-artifact@v3
        with:
          path: "./playwright-tests/*.png"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
