name: Playwright Tests
on:
  - push
  - workflow_dispatch

jobs:
  test:
    timeout-minutes: 13
    runs-on: ubuntu-20.04
    steps:
      - name: Print branch name
        shell: bash
        run: echo "${GITHUB_HEAD_REF}"
      - uses: actions/checkout@v3
        with:
          submodules: 'true' # TODO recursive? True seems to work however
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Frontend
        run: ./build.sh
        #TODO zip ui artifacts here

      # TODO check if branch exists (script) and use it, otherwise use HEAD (eaas-server@branch-name)
      - name: Check if backend branch with same name exists
        run: |
          check_branch=$(git ls-remote --heads https://github.com/emulation-as-a-service/eaas-server.git ${{ github.ref_name }})
          echo "Branch:"
          echo "$check_branch"
          if [[ -z ${check_branch} ]]; then
              echo "SERVER_BRANCH=''" >> $GITHUB_ENV
          else
              echo "SERVER_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
        with:
          repository: emulation-as-a-service/eaas-server
          ref: ${{env.SERVER_BRANCH}}
          path: ./eaas-server
      - name: Build Server
        run: ./compile-locally.sh # eaas-server/src/ear/target/eaas-server.ear
        working-directory: ./eaas-server
      - uses: emulation-as-a-service/eaas-installer@github-actions
        with:
          isBackend: false
          branch: ${GITHUB_HEAD_REF}
          # TODO Installer should use eaas-frontend-admin/dist and eaas-server/src/ear/target/eaas-server.ear for deployment
      - name: Install dependencies
        run: npm ci
        working-directory: ./playwright-tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./playwright-tests
      - name: Run Playwright tests
        run: npx playwright test --project=chromium
        working-directory: ./playwright-tests
      - uses: actions/upload-artifact@v3
        with:
          path: "./playwright-tests/*.png"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
