name: Playwright Tests
on:
  - push
  - workflow_dispatch

jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-20.04
    steps:
      - name: Print branch name
        shell: bash
        run: echo "${GITHUB_HEAD_REF}"
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Frontend # result: eaas-frontend-admin/dist landing-page/dist
        run: ./build.sh
      - name: Zip Frontend
        run: zip -r eaas_ui.zip eaas-frontend-admin/dist landing-page/dist
        shell: bash
      - name: Check if backend branch with same name exists
        run: |
          check_branch=$(git ls-remote --heads https://github.com/emulation-as-a-service/eaas-server.git ${{ github.ref_name }})
          echo "Branch:"
          echo "$check_branch"
          if [[ -z ${check_branch} ]]; then
              echo "SERVER_BRANCH=master" >> "$GITHUB_ENV"
          else
              echo "SERVER_BRANCH=${{ github.ref_name }}" >> "$GITHUB_ENV"
          fi
      - name: Print Used Server branch
        run: echo ${{env.SERVER_BRANCH}} && echo "$SERVER_BRANCH"
      - uses: actions/checkout@v3
        with:
          repository: emulation-as-a-service/eaas-server
          ref: ${{env.SERVER_BRANCH}}
          path: ./eaas-server
      - name: Build Server
        run: ./compile-locally.sh # result: eaas-server/src/ear/target/eaas-server.ear
        working-directory: ./eaas-server
      - uses: emulation-as-a-service/eaas-installer
        env:
          eaas_server_url: "./eaas-server/src/ear/target/eaas-server.ear"
          eaas_ui_url: "./eaas_ui.zip"
          wait_for_eaas_server: true

      - name: Install dependencies
        run: npm ci
        working-directory: ./playwright-tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./playwright-tests
      - name: Run Playwright tests
        run: npx playwright test --project=chromium
        working-directory: ./playwright-tests
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: "./playwright-tests/test-results/"
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: html-report
          path: "./playwright-tests/html-report/"
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: json-report
          path: "./playwright-tests/json-report.json"
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: eaas-server-logs
          path: "/eaas-home/log/server/server.log"
          retention-days: 30
